### ISSUE TITLE
На дистанции вылетел баг.

### ISSUE THREAD

**Issue by Murlakotamus** [Murlakotamus/Boggarton#156]
/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/java -Djava.library.path=target/natives -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=62778:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/lib/tools.jar:/Users/mdoumin/Work/Workspace/Boggarton/target/classes:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/lwjgl_util/2.9.0/lwjgl_util-2.9.0.jar:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/lwjgl/2.9.0/lwjgl-2.9.0.jar:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-windows.jar:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-linux.jar:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/lwjgl-platform/2.9.0/lwjgl-platform-2.9.0-natives-osx.jar:/Users/mdoumin/.m2/repository/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/mdoumin/.m2/repository/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/mdoumin/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-linux.jar:/Users/mdoumin/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-windows.jar:/Users/mdoumin/.m2/repository/net/java/jinput/jinput-platform/2.0.5/jinput-platform-2.0.5-natives-osx.jar:/Users/mdoumin/.m2/repository/org/lwjgl/lwjgl/3.1.0/lwjgl-3.1.0.jar:/Users/mdoumin/.m2/repository/com/yuvimasory/orange-extensions/1.3.0/orange-extensions-1.3.0.jar:/Users/mdoumin/.m2/repository/org/xerial/sqlite-jdbc/3.23.1/sqlite-jdbc-3.23.1.jar com.foxcatgames.boggarton.Boggarton
2024-06-10 19:20:47.054 java[30348:4675361] Unknown modifier with keycode: 0
2024-06-10 20:08:41.611 java[30348:4675361] Unknown modifier with keycode: 0
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -2
	at com.foxcatgames.boggarton.entity.Brick.draw(Brick.java:53)
	at com.foxcatgames.boggarton.engine.Layer.render(Layer.java:31)
	at com.foxcatgames.boggarton.scenes.AbstractScene.renderScene(AbstractScene.java:51)
	at com.foxcatgames.boggarton.scenes.AbstractScene.run(AbstractScene.java:59)
	at com.foxcatgames.boggarton.scenes.AbstractScene.play(AbstractScene.java:40)
	at com.foxcatgames.boggarton.Boggarton.run(Boggarton.java:11)
	at com.foxcatgames.boggarton.Boggarton.main(Boggarton.java:18)
 
![изображение](https://github.com/Murlakotamus/Boggarton/assets/32313160/6d0c91c0-1174-45b0-ac19-c6291c153736)

**Comment by Murlakotamus** [comment]
Что-то поправили. Проверим, когда будет больше времени.
